apiVersion: v2
name: redis
description: Redis helm chart.
type: application
version: 1.0.0

dependencies:
  # https://github.com/bitnami/charts/tree/master/bitnami
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 16.13.2
